### ISSUE TITLE
Add project version to CSS and JS files

### ISSUE THREAD

**Issue by henno** [henno/halo#7]
```
<script src="assets/js/main.js?v=<?= PROJECT_VERSION?>"></script>
<link href="assets/css/main.css?v=<?= PROJECT_VERSION?>" rel="stylesheet">
```

**Comment by Nuffic** [comment]
Ever heard of asset managers? :) This is shooting yourself in the foot. Wordpress does the same thing. Basicly when you want to update your assets w/o changing versions, old assets will be cached

**Comment by henno** [comment]
Project version is taken from git commit. When you change composer.lock, you make a new commit and a new commit hash is created by git which is automatically appended to CSS file urls as a query parameter which causes the file to be treated as a new file.
